tidy_name_func <-
        function(x) {
                
                x<-gsub("category_memory", "category_memory_game", x)
                x<-gsub("category_spiessecret_agents", "category_spies_secret_agents", x)
                x<-gsub("category_deduction", "category_deduction_game", x)
                x<-gsub("mechanic_deduction", "mechanic_deduction_mechanicanic", x)
                x<-gsub("category_novelbased", "category_novel_based", x)
                x<-gsub("category_realtime", "category_realtime_game", x)
                x<-gsub("category_miniatures", "category_miniatures_game", x)
                x<-gsub("family_components_miniatures", "has_miniatures", x)
                x<-gsub("mechanic_realtime", "mechanic_realtime_mechanicanic", x)
                x<-gsub("mechanic_memory", "mechanic_memory_mechanic", x)
                x<-gsub("family_components_miniatures", "has_miniatures", x)
                x<-gsub("designer_uncredited", "uncredited_designer", x)
                x<-gsub("trunc_", "", x)
                x<-gsub("category_","", x)
                x<-gsub("components_", "", x)
                x<-gsub("country_", "", x)
                x<-gsub("mechanic_","", x)
                x<-gsub("publisher_","", x)
                x<-gsub("designer_","", x)
                x<-gsub("theme_", "", x)
                x<-gsub("family_", "", x)
                x<-gsub("players_", "", x)
                x<-gsub("avgweight", "Average Weight", x)
                x<-gsub("yearpublished", "Year Published", x)
                x<-gsub("minage", "Min Age", x)
                x<-gsub("playingtime", "Playing Time", x)
                x<-gsub("maxplayers", "Max Players", x)
                x<-gsub("minplayers", "Min Players", x)
                x<-gsub("_", " ", x)
                
                
                x = str_to_title(x)
                x = gsub("Cut Playing Time X", "Playing Time", x)
                x = gsub("Rockpaperscissors", "Rock Paper Scissors", x)
                x = gsub("Collectible Collectible", "Collectible", x)
                x = gsub("Murdermystery", "Murder Mystery", x)
                x = gsub("Bgg Average", "BGG Average", x)
                x = gsub("World War Ii", "World War II", x)
                x = gsub("Gemscrystals", "Gems & Crystals", x)
                x = gsub("History ", "", x)
                x = gsub("Gmt", "GMT", x)
                x = gsub("Cmon", "CMON", x)
                x = gsub("Zman", "ZMan", x)
                x = gsub("Movies Tv", "Movies TV", x)
                x = gsub("Auctionbidding", "Auction Bidding", x)
                x = gsub("Postnapoleonic", "Post Napoleonic", x)
                x = gsub("Paperandpencil", "Paper And Pencil", x)
                x = gsub("Digital Hybrid Appwebsite Required", "Digital Hybrid App", x)
                x = gsub("3dimensional", "", x)
                x = gsub("3d", "3D", x)
                x = gsub("Usa", "USA", x)
                x = gsub("Averageweight", "Average Weight", x)
                x
                
        }
