---
title: "Predicting Upcoming Games for Reviewers"
output: 
  html_document:
    toc: TRUE #adds a Table of Contents
    number_sections: TRUE #number your headings/sections
    toc_float: TRUE #let your ToC follow you as you scroll
    keep_md: no
    fig.caption: yes
---

```{r load and set packages, echo=F, warning=F, message=F,  results = 'hide', include=F}

knitr::opts_chunk$set(echo = F,
                      error = F,
                      warning=F,
                      dev="png",
                      fig.width = 10,
                      fig.height = 6)

options(knitr.duplicate.label = "allow")

options(scipen=999)

#source
source(here::here("scripts/load_packages.R"))
source(here::here("functions/theme_phil.R"))
library(patchwork)
library(DT)

# set_flextable_defaults(theme_fun = theme_booktabs,
#                        font.color = "black",
#   padding.bottom = 6, 
#   padding.top = 6,
#   padding.left = 6,
#   padding.right = 6,
#   background.color = "white")

library(flextable)
set_flextable_defaults(theme_fun = theme_alafoli,
                       font.color = "grey10",
  padding.bottom = 6, 
  padding.top = 6,
  padding.left = 6,
  padding.right = 6,
  background.color = "white")

```


```{r reviewers tidied}

# list of reviewers
reviewers = c("Gyges",
               "ZeeGarcia",
               "Quinns",
               "rahdo",
               "Watch%20It%20Played",
               "J_3MBG",
               "VWValker",
               "aboardgamebarrage",
          #     "markbesada",
           #    "Neilan",
               "Alabaster%20Crippens")

# tidy
reviewers_tidied = gsub("%20", "", reviewers)

# make function for displaying in flextables
display_name_func = function(x) {
        
        x %>%
                gsub("%20", "", .) %>%
                abbreviate(., minlength=10) %>%
                str_pad(., width=10, side = "both")
               
}

# make df with versions of names
reviewers_df = data.frame("username" = reviewers,
                          "username_tidied" = gsub("%20", "", reviewers),
                          "username_abbr" = display_name_func(reviewers))
               
```

```{r rando df}

 
df = tibble("username" = reviewers_tidied) %>%
        mutate(data = map(username, ~ runif(1000, 0 ,1) %>% as_tibble()))

# function for adding color to flextables
col_func<- function(x) {
  
  breaks<-seq(0, 1, .01)
  
#  breaks = weight_deciles
  colorRamp=colorRampPalette(c("white", "deepskyblue1"))
  col_palette <- colorRamp(length(breaks))
  mycut <- cut(x, 
    breaks = breaks,
    include.lowest = TRUE, 
    right=T,
    label = FALSE)
  col_palette[mycut]
  
}


df %>% 
        unnest(data) %>%
        left_join(., reviewers_df %>%
                          mutate(username = username_tidied),
                  by = c("username")) %>%
        select(-username, -username_tidied) %>%
        group_by(username_abbr) %>%
        mutate(ID = row_number()) %>%
        spread(username_abbr, value) %>%
        ungroup() %>%
        mutate_if(is.numeric, round, 2) %>%
        flextable() %>%
  #      width(j = reviewers_tidied, width = 1, unit = "in") %>%
        bg(j = reviewers_df$username_abbr,
           bg = col_func) %>%
        flextable::align(j = reviewers_df$username_abbr,
              part = 'all',
              align = 'center') %>%
        set_header_labels(values = c("ID", reviewers_df$username_abbr)) %>%
        autofit()


```

